### ISSUE TITLE
Error encoding objects with custom objects as properties

### ISSUE THREAD

**Issue by mccrackend** [PlanetCache/CacheJSON#2]
Getting a <COMMAND>zEncode+11^CacheJSON error trying to encode Sample.Person object that contains properties for Home and Office of type Sample.Address.  Extending CacheJSON on the Address class results in a similar error.  This checking for custom object properties may need to occur inside the Encode() method.

``` ruby
Set list = ##class(%ListOfDataTypes).%New()
For x=1:1:size {
	Set obj = ##class(Sample.Person).%OpenId(x)
	Set sc = list.Insert(obj.GetAsArrayOfDataTypes())
}
Set encodedList = ##class(Sample.Person).Encode(list)
W !, !, "Encoded list of objects: " _ encodedList
Quit
````

**Comment by uvg** [comment]
Look at the bug fix in the pull requests
